importsysimporttimeimportjsonimportrequestsfrompathlibimportPathdeftest_web_interface():
"""Testwebinterface"""
print("LLMAdvancedTestingSuite-WebInterfaceTest")
print("="*50)
base_url="http://localhost"
test_results=[]
#Test1:Checkwebinterfacestatusprint("\nTest1:Checkwebinterfacestatus")
try:
response=requests.get(f"{base_url}/",timeout=5)
ifresponse.status_code==200:
print("PASS:Webinterfaceisrunning")
test_results.append({"test":"Webinterfacestatus","status":"PASS","message":"Webinterfaceisrunning"})
else:
print(f"FAIL:Webinterfacereturnederrorstatus:{response.status_code}")
test_results.append({"test":"Webinterfacestatus","status":"FAIL","message":f"Statuscode:{response.status_code}"})
exceptExceptionase:
print(f"FAIL:Webinterfaceisnotrunning:{e}")
test_results.append({"test":"Webinterfacestatus","status":"FAIL","message":f"Connectionfailed:{e}"})
#Test2:CheckAPIendpointsprint("\nTest2:CheckAPIendpoints")
api_endpoints=["/api/models","/api/tests","/api/results"]
forendpointinapi_endpoints:
try:
response=requests.get(f"{base_url}{endpoint}",timeout=5)
ifresponse.status_code==200:
print(f"PASS:{endpoint}isnormal")
test_results.append({"test":f"APIendpoint{endpoint}","status":"PASS","message":"Normal"})
else:
print(f"FAIL:{endpoint}returnederror:{response.status_code}")
test_results.append({"test":f"APIendpoint{endpoint}","status":"FAIL","message":f"Statuscode:{response.status_code}"})
exceptExceptionase:
print(f"FAIL:{endpoint}connectionfailed:{e}")
test_results.append({"test":f"APIendpoint{endpoint}","status":"FAIL","message":f"Connectionfailed:{e}"})
#Test3:Checkfunctionalityprint("\nTest3:Checkfunctionality")
try:
test_data={
"pillar_name":"pillar_01_logic",
"prompt":"Testprompt",
"model_name":"test_model"
}
response=requests.post(
f"{base_url}/api/run_test",
json=test_data,
headers={"Content-Type":"application/json"},
timeout=10)
ifresponse.status_code==200:
print("PASS:run_testfunctionalityisnormal")
test_results.append({"test":"run_testfunctionality","status":"PASS","message":"Functionalityisnormal"})
else:
print(f"FAIL:run_testfunctionalityerror:{response.status_code}")
test_results.append({"test":"run_testfunctionality","status":"FAIL","message":f"Statuscode:{response.status_code}"})
exceptExceptionase:
print(f"FAIL:run_testfunctionalityfailed:{e}")
test_results.append({"test":"run_testfunctionality","status":"FAIL","message":f"Connectionfailed:{e}"})
#Generatereportprint("\nGeneratetestreport")
#Countresultstotal_tests=len(test_results)
passed_tests=len([rforrintest_resultsifr["status"]=="PASS"])
failed_tests=len([rforrintest_resultsifr["status"]=="FAIL"])
print(f"Totaltests:{total_tests}")
print(f"Passedtests:{passed_tests}")
print(f"Failedtests:{failed_tests}")
iftotal_tests>0:
success_rate=(passed_tests/total_tests)*100print(f"Successrate:{success_rate:.1f}%")
#Savereportreport_file=Path("test_reports/final_solution_report.json")
report_file.parent.mkdir(parents=True,exist_ok=True)
report_data={
"timestamp":time.strftime("%Y-%m-%d%H:%M:%S"),
"total_tests":total_tests,
"passed_tests":passed_tests,
"failed_tests":failed_tests,
"success_rate":(passed_tests/total_tests)*100iftotal_tests>0else0,
"results":test_results}
withopen(report_file,'w',encoding='utf-8')asf:
json.dump(report_data,f,indent=2,ensure_ascii=False)
print(f"Reportsaved:{report_file}")
#Outputfinalresultprint("\n"+"="*50)
ifpassed_tests==total_tests:
print("SUCCESS:Alltestspassed!Localwebinterfaceisrunningnormally!")
print(f"AccessURL:{base_url}")
print("Finalsolutionsuccessful!")
else:
print("FAIL:Sometestsfailed!Needtofix!")
print("Pleasecheckiflocalwebinterfaceisrunningnormally")
returnpassed_tests==total_testsif__name__=="__main__":
success=test_web_interface()
sys.exit(0ifsuccesselse1)